const ALCANCE = {
  INDIVIDUAL: "INDIVIDUAL",
  GENERAL: "GENERAL",
  DEPARTAMENTO: "DEPARTAMENTO",
  SUCURSAL: "SUCURSAL",
};

const TIPO = {
  DIRECTA: "DIRECTA",
  COMUNICADO: "COMUNICADO",
  CIRCULAR: "CIRCULAR",
  REGLAMENTO: "REGLAMENTO",
};

const ESTADO_MENSAJE = {
  NO_LEIDO: "NO_LEIDO",
  LEIDO: "LEIDO",
  CONFIRMADO: "CONFIRMADO",
};

// Mapeos por defecto a los IDs generados por identidad
const ALCANCE_ID = {
  [ALCANCE.INDIVIDUAL]: 1,
  [ALCANCE.GENERAL]: 2,
  [ALCANCE.DEPARTAMENTO]: 3,
  [ALCANCE.SUCURSAL]: 4,
};

const TIPO_ID = {
  [TIPO.DIRECTA]: 1,
  [TIPO.COMUNICADO]: 2,
  [TIPO.CIRCULAR]: 3,
  [TIPO.REGLAMENTO]: 4,
};

const ESTADO_MENSAJE_ID = {
  [ESTADO_MENSAJE.NO_LEIDO]: 1,
  [ESTADO_MENSAJE.LEIDO]: 2,
  [ESTADO_MENSAJE.CONFIRMADO]: 3,
};

module.exports = {
  ALCANCE,
  TIPO,
  ESTADO_MENSAJE,
  ALCANCE_ID,
  TIPO_ID,
  ESTADO_MENSAJE_ID,
};
