/**
 * Automated Test Suite: RF-09 Applicant Registration Acceptance Criteria
 *
 * Covers all 4 Acceptance Criteria and error boundary scenarios:
 *  - AC 1: Valid registration saves applicant info & associates with job opening
 *  - AC 2: Duplicate ID registration for same opening is flagged & no 2nd record created
 *  - AC 3: Missing required fields prevent registration and indicate missing data
 *  - AC 4: Recruiter views job opening and gets applicant list with application dates
 */

const path = require("path");
require("dotenv").config({ path: path.resolve(__dirname, "../.env") });
const { Pool } = require("pg");

const API_BASE =
  process.env.API_BASE || `http://localhost:${process.env.PORT || 3003}`;

const pool = new Pool(
  process.env.DATABASE_URL
    ? { connectionString: process.env.DATABASE_URL }
    : undefined
);

// Seed opening IDs
const OPENING_ACTIVE_1 = "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11"; // Full Stack Senior
const OPENING_ACTIVE_2 = "b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a22"; // Analista Talento
const OPENING_INACTIVE = "c2eebc99-9c0b-4ef8-bb6d-6bb9bd380a33"; // UI/UX Inactiva
const OPENING_EXPIRED  = "d3eebc99-9c0b-4ef8-bb6d-6bb9bd380a44"; // Deadline passed
const NON_EXISTENT_UUID = "99999999-9999-9999-9999-999999999999";

// Specific test documents to clean without touching real applicant records
const TEST_DOCUMENTS = [
  "87654321",
  "65432109",
  "55443322",
  "44332211",
  "99887766",
  "76543210",
  "77112233",
  "88223344",
  "33445566",
  "22334455",
  "123",
];

// Test counters
let totalTests = 0;
let passedTests = 0;
let failedTests = 0;
const results = [];

function recordResult(criterion, testName, passed, details) {
  totalTests++;
  if (passed) {
    passedTests++;
    console.log(`  ✅ [PASS] ${testName}`);
  } else {
    failedTests++;
    console.error(`  ❌ [FAIL] ${testName}`);
    console.error(`     Details:`, details);
  }
  results.push({ criterion, testName, passed, details });
}

async function apiRequest(endpoint, options = {}) {
  const url = `${API_BASE}${endpoint}`;
  const response = await fetch(url, {
    headers: {
      "Content-Type": "application/json",
      ...(options.headers || {}),
    },
    ...options,
  });
  let body = null;
  try {
    body = await response.json();
  } catch (e) {
    body = null;
  }
  return { status: response.status, body };
}

/**
 * Non-destructive cleanup: only deletes records generated by this test suite,
 * preserving any real candidate data in the database.
 */
async function cleanTestData() {
  console.log("\n🧹 Cleaning test-specific applicant data from DB (non-destructive)...");
  await pool.query(
    `DELETE FROM POSTULACIONES 
     WHERE id_postulante IN (
       SELECT id_postulante FROM POSTULANTES 
       WHERE numero_documento = ANY($1)
          OR correo_electronico LIKE '%@testempresa.com'
          OR correo_electronico LIKE '%@test.com'
     );`,
    [TEST_DOCUMENTS]
  );
  await pool.query(
    `DELETE FROM POSTULANTES 
     WHERE numero_documento = ANY($1)
        OR correo_electronico LIKE '%@testempresa.com'
        OR correo_electronico LIKE '%@test.com';`,
    [TEST_DOCUMENTS]
  );
  console.log("   Done. Non-destructive cleanup completed.");
}

/**
 * Ensures test openings and catalog exist so test suite runs self-contained.
 */
async function ensureTestSeedData() {
  await pool.query(`
    INSERT INTO CATALOGOS_ETAPA_POSTULACION (id_etapa, codigo, nombre, orden_flujo) VALUES
    (1, 'POSTULADO', 'Postulación Recibida', 1),
    (2, 'REVISION_CV', 'Revisión Curricular', 2),
    (3, 'ENTREVISTA', 'Entrevista', 3),
    (4, 'EVALUACION', 'Evaluación Técnica', 4),
    (5, 'FINALISTA', 'Finalista / Oferta', 5),
    (6, 'CONTRATADO', 'Contratado', 6),
    (7, 'RECHAZADO', 'No Seleccionado', 7)
    ON CONFLICT (id_etapa) DO NOTHING;
  `);

  await pool.query(`
    INSERT INTO CONVOCATORIAS (
      id_convocatoria, id_cargo_referencial, id_sucursal_destino,
      codigo_convocatoria, titulo_puesto, descripcion_puesto,
      cantidad_vacantes, year_experiencia_min, nivel_educacion_min,
      habilidades_clave_requeridas, fecha_publicacion, fecha_limite_postulacion, esta_activa
    ) VALUES 
    (
      '${OPENING_ACTIVE_1}', '00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001',
      'CONV-TEST-001', 'Desarrollador Full Stack Senior', 'Puesto para pruebas automatizadas',
      2, 3.0, 'Licenciatura', ARRAY['Node.js', 'React', 'PostgreSQL'],
      CURRENT_DATE - INTERVAL '5 days', CURRENT_DATE + INTERVAL '30 days', TRUE
    ),
    (
      '${OPENING_ACTIVE_2}', '00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001',
      'CONV-TEST-002', 'Analista de Talento Humano', 'Puesto secundario para pruebas',
      1, 1.5, 'Licenciatura', ARRAY['Reclutamiento', 'Entrevistas'],
      CURRENT_DATE - INTERVAL '2 days', CURRENT_DATE + INTERVAL '15 days', TRUE
    ),
    (
      '${OPENING_INACTIVE}', '00000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000001',
      'CONV-TEST-003', 'Diseñador UI/UX Inactiva', 'Puesto cerrado para pruebas',
      1, 2.0, 'Licenciatura', ARRAY['Figma', 'UX Research'],
      CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE - INTERVAL '5 days', FALSE
    ),
    (
      '${OPENING_EXPIRED}', '00000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000001',
      'CONV-TEST-004', 'Convocatoria Vencida', 'Puesto con fecha límite expirada',
      1, 1.0, 'Licenciatura', ARRAY['QA', 'Testing'],
      (CURRENT_TIMESTAMP AT TIME ZONE 'America/La_Paz')::date - INTERVAL '30 days',
      (CURRENT_TIMESTAMP AT TIME ZONE 'America/La_Paz')::date - INTERVAL '2 days',
      TRUE
    )
    ON CONFLICT (id_convocatoria) DO UPDATE SET
      esta_activa = EXCLUDED.esta_activa,
      fecha_limite_postulacion = EXCLUDED.fecha_limite_postulacion;
  `);
}

async function runTestSuite() {
  console.log("================================================================================");
  console.log("🧪 RUNNING ACCEPTANCE CRITERIA & ERROR BOUNDARY TESTS (RF-09)");
  console.log("================================================================================\n");

  await ensureTestSeedData();
  await cleanTestData();

  // ============================================================================
  // CRITERION 1: Happy Path Registration & Job Opening Association
  // ============================================================================
  console.log("\n--- CRITERION 1: Save Applicant Information & Associate with Job Opening ---");

  // Test 1.1: Register valid applicant
  const applicant1 = {
    id_convocatoria: OPENING_ACTIVE_1,
    numero_documento: "87654321",
    nombres: "Carlos Alberto",
    apellidos: "Gómez Pérez",
    correo_electronico: "carlos.gomez@testempresa.com",
    telefono_contacto: "+591 71234567",
    direccion_residencia: "Av. 6 de Agosto #2450, Sopocachi",
    ciudad: "La Paz",
  };

  const res1_1 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(applicant1),
  });

  const pass1_1 =
    res1_1.status === 201 &&
    res1_1.body?.success === true &&
    res1_1.body?.data?.postulante?.numero_documento === applicant1.numero_documento &&
    res1_1.body?.data?.postulacion?.id_convocatoria === OPENING_ACTIVE_1 &&
    !!res1_1.body?.data?.postulacion?.fecha_postulacion;

  recordResult(
    "Criterion 1",
    "1.1 Successful registration with valid data (HTTP 201 + association created)",
    pass1_1,
    res1_1
  );

  // Test 1.2: Verify DB persistence
  const dbCheck1 = await pool.query(
    `SELECT p.id_postulante, p.numero_documento, p.nombres, p.apellidos, 
            pos.id_postulacion, pos.id_convocatoria, pos.id_etapa, pos.fecha_postulacion
     FROM POSTULANTES p
     JOIN POSTULACIONES pos ON pos.id_postulante = p.id_postulante
     WHERE p.numero_documento = $1 AND pos.id_convocatoria = $2;`,
    [applicant1.numero_documento, OPENING_ACTIVE_1]
  );

  const pass1_2 =
    dbCheck1.rowCount === 1 &&
    dbCheck1.rows[0].numero_documento === applicant1.numero_documento &&
    dbCheck1.rows[0].id_convocatoria === OPENING_ACTIVE_1 &&
    dbCheck1.rows[0].id_etapa === 1;

  recordResult(
    "Criterion 1",
    "1.2 Verify persistence in DB (POSTULANTES and POSTULACIONES records match)",
    pass1_2,
    dbCheck1.rows[0]
  );

  // Test 1.3: Error - Register to inactive job opening
  const applicantInactive = {
    id_convocatoria: OPENING_INACTIVE,
    numero_documento: "55443322",
    nombres: "Mariana",
    apellidos: "López Silva",
    correo_electronico: "mariana.lopez@testempresa.com",
    telefono_contacto: "72345678",
  };

  const res1_3 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(applicantInactive),
  });

  const pass1_3 =
    res1_3.status === 400 &&
    res1_3.body?.success === false &&
    res1_3.body?.message?.includes("activa");

  recordResult(
    "Criterion 1 (Error Handling)",
    "1.3 Attempt to register for inactive job opening is rejected (HTTP 400)",
    pass1_3,
    res1_3
  );

  // Test 1.4: Error - Register to non-existent job opening UUID
  const applicantNotFound = {
    id_convocatoria: NON_EXISTENT_UUID,
    numero_documento: "44332211",
    nombres: "Rodrigo",
    apellidos: "Chavez",
    correo_electronico: "rodrigo.chavez@testempresa.com",
    telefono_contacto: "73456789",
  };

  const res1_4 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(applicantNotFound),
  });

  const pass1_4 =
    res1_4.status === 404 &&
    res1_4.body?.success === false &&
    res1_4.body?.message?.includes("no existe");

  recordResult(
    "Criterion 1 (Error Handling)",
    "1.4 Attempt to register for non-existent job opening is rejected (HTTP 404)",
    pass1_4,
    res1_4
  );

  // Test 1.5: Register existing applicant to a SECOND different job opening
  const applicant1_opening2 = {
    id_convocatoria: OPENING_ACTIVE_2,
    numero_documento: applicant1.numero_documento, // Same document
    nombres: applicant1.nombres,
    apellidos: applicant1.apellidos,
    correo_electronico: applicant1.correo_electronico,
    telefono_contacto: applicant1.telefono_contacto,
  };

  const res1_5 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(applicant1_opening2),
  });

  const pass1_5 =
    res1_5.status === 201 &&
    res1_5.body?.success === true &&
    res1_5.body?.data?.postulacion?.id_convocatoria === OPENING_ACTIVE_2;

  recordResult(
    "Criterion 1",
    "1.5 Register same applicant to a DIFFERENT active opening succeeds (reuses applicant record)",
    pass1_5,
    res1_5
  );

  // Test 1.6: Reject registration for vacancy whose deadline has passed (Lock check)
  const applicantExpired = {
    id_convocatoria: OPENING_EXPIRED,
    numero_documento: "99887766",
    nombres: "Lucía",
    apellidos: "Rojas",
    correo_electronico: "lucia.rojas@testempresa.com",
    telefono_contacto: "71987654",
  };

  const res1_6 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(applicantExpired),
  });

  const pass1_6 =
    res1_6.status === 400 &&
    res1_6.body?.success === false &&
    (res1_6.body?.message?.includes("fecha límite") ||
     res1_6.body?.message?.includes("activa"));

  recordResult(
    "Criterion 1 (Business Rule - Lock)",
    "1.6 Vacancy past its deadline is rejected (HTTP 400, fecha límite vencida)",
    pass1_6,
    res1_6
  );

  // Test 1.7: Expired vacancies are not returned in active job openings list
  const res1_7 = await apiRequest("/applicants/job-openings");
  const activeOpenings = res1_7.body?.data || [];
  const expiredExcluded = !activeOpenings.some(
    (o) => o.id_convocatoria === OPENING_EXPIRED
  );

  const pass1_7 = res1_7.status === 200 && expiredExcluded;

  recordResult(
    "Criterion 1 (Dropdown Filter)",
    "1.7 Expired vacancy is excluded from active job openings dropdown list",
    pass1_7,
    { totalActiveReturned: activeOpenings.length, expiredExcluded }
  );

  // Test 1.8: Preserving returning candidate's saved details (María's city "El Alto" test)
  const mariaFirst = {
    id_convocatoria: OPENING_ACTIVE_1,
    numero_documento: "77112233",
    nombres: "María",
    apellidos: "Quispe Mamani",
    correo_electronico: "maria.quispe@testempresa.com",
    telefono_contacto: "72233445",
    direccion_residencia: "Av. Panorámica #123, Zona 16 de Julio",
    ciudad: "El Alto",
  };

  await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(mariaFirst),
  });

  // Second application leaving optional ciudad and direccion_residencia empty
  const mariaSecond = {
    id_convocatoria: OPENING_ACTIVE_2,
    numero_documento: "77112233",
    nombres: "María",
    apellidos: "Quispe Mamani",
    correo_electronico: "maria.quispe@testempresa.com",
    telefono_contacto: "72233445",
    direccion_residencia: "",
    ciudad: "",
  };

  const res1_8 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(mariaSecond),
  });

  const mariaDb = await pool.query(
    `SELECT ciudad, direccion_residencia FROM POSTULANTES WHERE numero_documento = '77112233';`
  );

  const pass1_8 =
    res1_8.status === 201 &&
    mariaDb.rows[0]?.ciudad === "El Alto" &&
    mariaDb.rows[0]?.direccion_residencia === "Av. Panorámica #123, Zona 16 de Julio";

  recordResult(
    "Criterion 1 (Data Preservation)",
    "1.8 Returning candidate's saved details (city/address) are NOT overwritten with empty fields",
    pass1_8,
    mariaDb.rows[0]
  );

  // Test 1.9: Transaction integrity: failed application leaves no orphan postulante row
  const invalidConvocatoriaAttempt = {
    id_convocatoria: NON_EXISTENT_UUID,
    numero_documento: "88223344",
    nombres: "Postulante Huérfano",
    apellidos: "Test Transacción",
    correo_electronico: "huerfano.test@testempresa.com",
    telefono_contacto: "76543211",
  };

  await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(invalidConvocatoriaAttempt),
  });

  const orphanCheck = await pool.query(
    `SELECT COUNT(*) AS total FROM POSTULANTES WHERE numero_documento = '88223344';`
  );

  const pass1_9 = parseInt(orphanCheck.rows[0].total, 10) === 0;

  recordResult(
    "Criterion 1 (Transaction Atomicity)",
    "1.9 Failure during application leaves zero orphan rows in POSTULANTES (ACID rollback)",
    pass1_9,
    `Total rows found: ${orphanCheck.rows[0].total}`
  );

  // ============================================================================
  // CRITERION 2: Duplicate ID Prevention for Same Job Opening
  // ============================================================================
  console.log("\n--- CRITERION 2: Duplicate ID Detection for Same Job Opening ---");

  // Test 2.1: Duplicate ID for same opening
  const duplicateAttempt = {
    id_convocatoria: OPENING_ACTIVE_1,
    numero_documento: applicant1.numero_documento, // "87654321" already registered in OPENING_ACTIVE_1
    nombres: "Carlos Alberto Duplicate",
    apellidos: "Gómez Pérez",
    correo_electronico: "carlos.gomez@testempresa.com",
    telefono_contacto: "+591 71234567",
  };

  const res2_1 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(duplicateAttempt),
  });

  const pass2_1 =
    res2_1.status === 409 &&
    res2_1.body?.success === false &&
    res2_1.body?.message?.includes(applicant1.numero_documento) &&
    res2_1.body?.message?.includes("ya se encuentra registrado");

  recordResult(
    "Criterion 2",
    "2.1 Attempt to register duplicate ID for same opening is blocked (HTTP 409 Conflict)",
    pass2_1,
    res2_1
  );

  // Test 2.2: Verify no second record was created in DB
  const dbCheck2 = await pool.query(
    `SELECT COUNT(*) AS total_postulaciones
     FROM POSTULACIONES pos
     JOIN POSTULANTES p ON p.id_postulante = pos.id_postulante
     WHERE p.numero_documento = $1 AND pos.id_convocatoria = $2;`,
    [applicant1.numero_documento, OPENING_ACTIVE_1]
  );

  const pass2_2 = parseInt(dbCheck2.rows[0].total_postulaciones, 10) === 1;

  recordResult(
    "Criterion 2",
    "2.2 DB verification: exactly 1 application record exists (no duplicate record created)",
    pass2_2,
    `Total records found: ${dbCheck2.rows[0].total_postulaciones}`
  );

  // Test 2.3: Duplicate with padded whitespace around document
  const duplicateWithSpaces = {
    id_convocatoria: OPENING_ACTIVE_1,
    numero_documento: `  ${applicant1.numero_documento}  `,
    nombres: "Carlos Alberto",
    apellidos: "Gómez",
    correo_electronico: "carlos.gomez@testempresa.com",
    telefono_contacto: "71234567",
  };

  const res2_3 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(duplicateWithSpaces),
  });

  const pass2_3 =
    res2_3.status === 409 &&
    res2_3.body?.success === false &&
    res2_3.body?.message?.includes("ya se encuentra registrado");

  recordResult(
    "Criterion 2 (Edge Case)",
    "2.3 Duplicate document with whitespace padding is trimmed and detected as duplicate (HTTP 409)",
    pass2_3,
    res2_3
  );

  // Test 2.4: Conflict - Same email with a DIFFERENT document number
  const conflictEmail = {
    id_convocatoria: OPENING_ACTIVE_1,
    numero_documento: "99887766", // Different doc
    nombres: "Otro Postulante",
    apellidos: "Test",
    correo_electronico: applicant1.correo_electronico, // Same email as applicant1
    telefono_contacto: "78901234",
  };

  const res2_4 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(conflictEmail),
  });

  const pass2_4 =
    res2_4.status === 409 &&
    res2_4.body?.success === false &&
    res2_4.body?.message?.includes("correo electrónico");

  recordResult(
    "Criterion 2 (Data Integrity)",
    "2.4 Conflict when using an existing email with a different ID number (HTTP 409)",
    pass2_4,
    res2_4
  );

  // ============================================================================
  // CRITERION 3: Missing Required Fields Validation
  // ============================================================================
  console.log("\n--- CRITERION 3: Missing Required Fields Validation ---");

  // Test 3.1: Completely empty payload
  const res3_1 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify({}),
  });

  const requiredFieldKeys = [
    "id_convocatoria",
    "numero_documento",
    "nombres",
    "apellidos",
    "correo_electronico",
    "telefono_contacto",
  ];

  const returnedErrorFields = (res3_1.body?.errors || []).map((e) => e.field);
  const allRequiredIndicated = requiredFieldKeys.every((f) =>
    returnedErrorFields.includes(f)
  );

  const pass3_1 =
    res3_1.status === 400 &&
    res3_1.body?.success === false &&
    allRequiredIndicated;

  recordResult(
    "Criterion 3",
    "3.1 Empty registration payload blocks submission and indicates ALL 6 missing fields",
    pass3_1,
    { returnedErrorFields }
  );

  // Test 3.2: Missing numero_documento
  const payloadNoDoc = {
    id_convocatoria: OPENING_ACTIVE_1,
    numero_documento: "",
    nombres: "Ana",
    apellidos: "Condori",
    correo_electronico: "ana.condori@test.com",
    telefono_contacto: "72345678",
  };
  const res3_2 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(payloadNoDoc),
  });
  const pass3_2 =
    res3_2.status === 400 &&
    res3_2.body?.errors?.some((e) => e.field === "numero_documento");
  recordResult(
    "Criterion 3",
    "3.2 Missing numero_documento prevents registration and indicates missing field",
    pass3_2,
    res3_2
  );

  // Test 3.3: Missing nombres (whitespace string)
  const payloadNoName = {
    id_convocatoria: OPENING_ACTIVE_1,
    numero_documento: "76543210",
    nombres: "   ",
    apellidos: "Condori",
    correo_electronico: "ana.condori@test.com",
    telefono_contacto: "72345678",
  };
  const res3_3 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(payloadNoName),
  });
  const pass3_3 =
    res3_3.status === 400 &&
    res3_3.body?.errors?.some((e) => e.field === "nombres");
  recordResult(
    "Criterion 3",
    "3.3 Whitespace-only nombres prevents registration and indicates missing field",
    pass3_3,
    res3_3
  );

  // Test 3.4: Missing apellidos
  const payloadNoSurname = {
    id_convocatoria: OPENING_ACTIVE_1,
    numero_documento: "76543210",
    nombres: "Ana",
    apellidos: "",
    correo_electronico: "ana.condori@test.com",
    telefono_contacto: "72345678",
  };
  const res3_4 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(payloadNoSurname),
  });
  const pass3_4 =
    res3_4.status === 400 &&
    res3_4.body?.errors?.some((e) => e.field === "apellidos");
  recordResult(
    "Criterion 3",
    "3.4 Missing apellidos prevents registration and indicates missing field",
    pass3_4,
    res3_4
  );

  // Test 3.5: Missing correo_electronico
  const payloadNoEmail = {
    id_convocatoria: OPENING_ACTIVE_1,
    numero_documento: "76543210",
    nombres: "Ana",
    apellidos: "Condori",
    correo_electronico: "",
    telefono_contacto: "72345678",
  };
  const res3_5 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(payloadNoEmail),
  });
  const pass3_5 =
    res3_5.status === 400 &&
    res3_5.body?.errors?.some((e) => e.field === "correo_electronico");
  recordResult(
    "Criterion 3",
    "3.5 Missing correo_electronico prevents registration and indicates missing field",
    pass3_5,
    res3_5
  );

  // Test 3.6: Missing telefono_contacto
  const payloadNoPhone = {
    id_convocatoria: OPENING_ACTIVE_1,
    numero_documento: "76543210",
    nombres: "Ana",
    apellidos: "Condori",
    correo_electronico: "ana.condori@test.com",
    telefono_contacto: "",
  };
  const res3_6 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(payloadNoPhone),
  });
  const pass3_6 =
    res3_6.status === 400 &&
    res3_6.body?.errors?.some((e) => e.field === "telefono_contacto");
  recordResult(
    "Criterion 3",
    "3.6 Missing telefono_contacto prevents registration and indicates missing field",
    pass3_6,
    res3_6
  );

  // Test 3.7: Missing id_convocatoria
  const payloadNoOpening = {
    id_convocatoria: "",
    numero_documento: "76543210",
    nombres: "Ana",
    apellidos: "Condori",
    correo_electronico: "ana.condori@test.com",
    telefono_contacto: "72345678",
  };
  const res3_7 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(payloadNoOpening),
  });
  const pass3_7 =
    res3_7.status === 400 &&
    res3_7.body?.errors?.some((e) => e.field === "id_convocatoria");
  recordResult(
    "Criterion 3",
    "3.7 Missing id_convocatoria prevents registration and indicates missing field",
    pass3_7,
    res3_7
  );

  // Test 3.8: Malformed email format
  const payloadBadEmail = {
    id_convocatoria: OPENING_ACTIVE_1,
    numero_documento: "76543210",
    nombres: "Ana",
    apellidos: "Condori",
    correo_electronico: "not-an-email-address",
    telefono_contacto: "72345678",
  };
  const res3_8 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(payloadBadEmail),
  });
  const pass3_8 =
    res3_8.status === 400 &&
    res3_8.body?.errors?.some((e) => e.field === "correo_electronico");
  recordResult(
    "Criterion 3 (Format Validation)",
    "3.8 Invalid email format is rejected and indicates field error",
    pass3_8,
    res3_8
  );

  // Test 3.9: Document number too short (< 5 chars)
  const payloadShortDoc = {
    id_convocatoria: OPENING_ACTIVE_1,
    numero_documento: "123", // too short
    nombres: "Ana",
    apellidos: "Condori",
    correo_electronico: "ana.condori@test.com",
    telefono_contacto: "72345678",
  };
  const res3_9 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(payloadShortDoc),
  });
  const pass3_9 =
    res3_9.status === 400 &&
    res3_9.body?.errors?.some((e) => e.field === "numero_documento");
  recordResult(
    "Criterion 3 (Format Validation)",
    "3.9 Document number shorter than 5 chars is rejected and indicates field error",
    pass3_9,
    res3_9
  );

  // Test 3.10: Phone number too short (< 7 digits)
  const payloadShortPhone = {
    id_convocatoria: OPENING_ACTIVE_1,
    numero_documento: "76543210",
    nombres: "Ana",
    apellidos: "Condori",
    correo_electronico: "ana.condori@test.com",
    telefono_contacto: "123", // too short
  };
  const res3_10 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(payloadShortPhone),
  });
  const pass3_10 =
    res3_10.status === 400 &&
    res3_10.body?.errors?.some((e) => e.field === "telefono_contacto");
  recordResult(
    "Criterion 3 (Format Validation)",
    "3.10 Phone number shorter than 7 digits is rejected and indicates field error",
    pass3_10,
    res3_10
  );

  // Test 3.11: Malformed UUID for id_convocatoria
  const payloadMalformedUuid = {
    id_convocatoria: "not-a-valid-uuid",
    numero_documento: "76543210",
    nombres: "Ana",
    apellidos: "Condori",
    correo_electronico: "ana.condori@test.com",
    telefono_contacto: "72345678",
  };
  const res3_11 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(payloadMalformedUuid),
  });
  const pass3_11 =
    res3_11.status === 400 &&
    res3_11.body?.errors?.some((e) => e.field === "id_convocatoria");
  recordResult(
    "Criterion 3 (Format Validation)",
    "3.11 Malformed id_convocatoria string returns clean HTTP 400 error instead of server crash",
    pass3_11,
    res3_11
  );

  // ============================================================================
  // CRITERION 4: Recruiter Views Job Opening & Sees Applicants with Dates
  // ============================================================================
  console.log("\n--- CRITERION 4: Recruiter Views Job Opening & Associated Applicants ---");

  // First, register a second applicant for OPENING_ACTIVE_1 to test listing multiple applicants
  const applicant2 = {
    id_convocatoria: OPENING_ACTIVE_1,
    numero_documento: "65432109",
    nombres: "Beatriz Elena",
    apellidos: "Vargas Flores",
    correo_electronico: "beatriz.vargas@testempresa.com",
    telefono_contacto: "76543210",
    direccion_residencia: "Calle Loayza #500",
    ciudad: "La Paz",
  };

  await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(applicant2),
  });

  // Test 4.1: Recruiter queries applicants for OPENING_ACTIVE_1
  const res4_1 = await apiRequest(`/applicants/by-opening/${OPENING_ACTIVE_1}`);

  const applicantsList = res4_1.body?.data?.postulantes || [];
  const pass4_1 =
    res4_1.status === 200 &&
    res4_1.body?.success === true &&
    applicantsList.length === 3 &&
    res4_1.body?.data?.convocatoria?.id_convocatoria === OPENING_ACTIVE_1;

  recordResult(
    "Criterion 4",
    "4.1 Recruiter retrieves list of applicants associated with the job opening (HTTP 200)",
    pass4_1,
    { count: applicantsList.length, total: res4_1.body?.data?.total_postulantes }
  );

  // Test 4.2: Verify every applicant in the list has an application date (fecha_postulacion)
  const allHaveDates = applicantsList.every(
    (app) => !!app.fecha_postulacion && !isNaN(Date.parse(app.fecha_postulacion))
  );
  const allHaveRequiredFields = applicantsList.every(
    (app) =>
      !!app.numero_documento &&
      !!app.nombres &&
      !!app.apellidos &&
      !!app.correo_electronico &&
      !!app.telefono_contacto
  );

  const pass4_2 = allHaveDates && allHaveRequiredFields;

  recordResult(
    "Criterion 4",
    "4.2 Each applicant record includes valid application date (fecha_postulacion) and complete details",
    pass4_2,
    applicantsList.map((a) => ({
      doc: a.numero_documento,
      name: `${a.nombres} ${a.apellidos}`,
      fecha: a.fecha_postulacion,
      etapa: a.nombre_etapa,
    }))
  );

  // Test 4.3: Verify sorting: most recent application first
  const date0 = new Date(applicantsList[0].fecha_postulacion).getTime();
  const date1 = new Date(applicantsList[1].fecha_postulacion).getTime();
  const pass4_3 = date0 >= date1;

  recordResult(
    "Criterion 4",
    "4.3 Applicants are ordered in descending chronological order (most recent first)",
    pass4_3,
    { firstDate: applicantsList[0]?.fecha_postulacion, secondDate: applicantsList[1]?.fecha_postulacion }
  );

  // Test 4.4: Recruiter queries job opening with zero applicants
  const res4_4 = await apiRequest(`/applicants/by-opening/${OPENING_INACTIVE}`);
  const pass4_4 =
    res4_4.status === 200 &&
    res4_4.body?.success === true &&
    res4_4.body?.data?.total_postulantes === 0 &&
    Array.isArray(res4_4.body?.data?.postulantes) &&
    res4_4.body?.data?.postulantes.length === 0;

  recordResult(
    "Criterion 4",
    "4.4 Opening with zero applicants returns empty list cleanly (HTTP 200, count 0)",
    pass4_4,
    res4_4
  );

  // Test 4.5: Recruiter queries non-existent job opening UUID
  const res4_5 = await apiRequest(`/applicants/by-opening/${NON_EXISTENT_UUID}`);
  const pass4_5 =
    res4_5.status === 404 &&
    res4_5.body?.success === false &&
    res4_5.body?.message?.includes("no existe");

  recordResult(
    "Criterion 4 (Error Handling)",
    "4.5 Querying non-existent job opening returns HTTP 404 cleanly",
    pass4_5,
    res4_5
  );

  // Test 4.6: Recruiter queries with invalid UUID format
  const res4_6 = await apiRequest(`/applicants/by-opening/not-a-valid-uuid`);
  const pass4_6 =
    res4_6.status === 400 &&
    res4_6.body?.success === false &&
    res4_6.body?.message?.includes("UUID");

  recordResult(
    "Criterion 4 (Error Handling)",
    "4.6 Querying with invalid UUID string returns HTTP 400 cleanly",
    pass4_6,
    res4_6
  );

  // --- REGRESSION & REVIEW CRITERIA TESTS ---
  console.log("\n--- REGRESSION & REVIEW CRITERIA TESTS ---");

  // Test 5.1: Concurrency - 20 simultaneous requests with SAME document number and DIFFERENT emails
  const concurrentDoc = "33445566";
  const concurrentPromises = [];
  for (let i = 1; i <= 20; i++) {
    concurrentPromises.push(
      apiRequest("/applicants/register", {
        method: "POST",
        body: JSON.stringify({
          id_convocatoria: OPENING_ACTIVE_1,
          numero_documento: concurrentDoc,
          nombres: `Postulante Concurrente ${i}`,
          apellidos: `Apellido ${i}`,
          correo_electronico: `concurrente_${i}@testempresa.com`,
          telefono_contacto: `700000${i.toString().padStart(2, "0")}`,
        }),
      })
    );
  }

  const concurrentResults = await Promise.all(concurrentPromises);
  const status201Count = concurrentResults.filter((r) => r.status === 201).length;
  const status409Count = concurrentResults.filter((r) => r.status === 409).length;

  const dbApplicants = await pool.query(
    `SELECT count(*) FROM POSTULANTES WHERE numero_documento = $1;`,
    [concurrentDoc]
  );
  const dbApplications = await pool.query(
    `SELECT count(*) FROM POSTULACIONES WHERE id_convocatoria = $1 AND id_postulante IN (
       SELECT id_postulante FROM POSTULANTES WHERE numero_documento = $2
     );`,
    [OPENING_ACTIVE_1, concurrentDoc]
  );

  const pass5_1 =
    status201Count === 1 &&
    status409Count === 19 &&
    parseInt(dbApplicants.rows[0].count, 10) === 1 &&
    parseInt(dbApplications.rows[0].count, 10) === 1;

  recordResult(
    "Regression (Concurrency)",
    "5.1 20 concurrent requests with same ID create exactly 1 applicant & 1 application (no duplicates)",
    pass5_1,
    { status201Count, status409Count, dbApplicants: dbApplicants.rows[0].count, dbApplications: dbApplications.rows[0].count }
  );

  // Test 5.2: Re-applying with same document number to another opening does NOT overwrite existing person
  const originalPerson = {
    id_convocatoria: OPENING_ACTIVE_1,
    numero_documento: "22334455",
    nombres: "Carlos Original",
    apellidos: "Condori Original",
    correo_electronico: "carlos.original@testempresa.com",
    telefono_contacto: "71234567",
  };
  await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(originalPerson),
  });

  // Re-apply to second opening with different name/email under same document
  const reApplyPerson = {
    id_convocatoria: OPENING_ACTIVE_2,
    numero_documento: "22334455",
    nombres: "Carlos Modificado",
    apellidos: "Condori Modificado",
    correo_electronico: "carlos.nuevo@testempresa.com",
    telefono_contacto: "79876543",
  };
  const res5_2 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(reApplyPerson),
  });

  const checkPersonDb = await pool.query(
    `SELECT nombres, apellidos, correo_electronico, telefono_contacto FROM POSTULANTES WHERE numero_documento = '22334455';`
  );

  const pass5_2 =
    res5_2.status === 201 &&
    checkPersonDb.rows[0]?.nombres === "Carlos Original" &&
    checkPersonDb.rows[0]?.apellidos === "Condori Original" &&
    checkPersonDb.rows[0]?.correo_electronico === "carlos.original@testempresa.com";

  recordResult(
    "Regression (Data Preservation)",
    "5.2 Re-applying does NOT overwrite the existing person's canonical profile",
    pass5_2,
    checkPersonDb.rows[0]
  );

  // Test 5.3: Validly formatted phone number over 20 chars returns 400 Bad Request, not 500
  const longPhoneApplicant = {
    id_convocatoria: OPENING_ACTIVE_1,
    numero_documento: "76543210",
    nombres: "Pedro",
    apellidos: "Gómez",
    correo_electronico: "pedro.longphone@testempresa.com",
    telefono_contacto: "+591 (2) 12345678-90123", // 24 chars, valid phone format but > 20 chars
  };
  const res5_3 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify(longPhoneApplicant),
  });

  const pass5_3 =
    res5_3.status === 400 &&
    res5_3.body?.success === false &&
    Array.isArray(res5_3.body?.detalles) &&
    res5_3.body.detalles.some((d) => d.field === "telefono_contacto" || d.campo === "telefono_contacto");

  recordResult(
    "Regression (Phone Validation)",
    "5.3 Phone number over 20 characters returns HTTP 400 with detalles (not 500)",
    pass5_3,
    res5_3
  );

  // Test 5.4: 400 response provides 'detalles' array for server-side field errors
  const res5_4 = await apiRequest("/applicants/register", {
    method: "POST",
    body: JSON.stringify({}),
  });
  const pass5_4 =
    res5_4.status === 400 &&
    Array.isArray(res5_4.body?.detalles) &&
    res5_4.body.detalles.length > 0;

  recordResult(
    "Regression (API Contract)",
    "5.4 Server 400 response includes detalles array matching UI form expectation",
    pass5_4,
    { hasDetalles: Array.isArray(res5_4.body?.detalles), count: res5_4.body?.detalles?.length }
  );

  // Test 5.5: 404 for missing opening has 'error' field
  const res5_5 = await apiRequest(`/applicants/by-opening/${NON_EXISTENT_UUID}`);
  const pass5_5 =
    res5_5.status === 404 &&
    Boolean(res5_5.body?.error);

  recordResult(
    "Regression (API Contract)",
    "5.5 404 response for missing opening includes error field",
    pass5_5,
    res5_5
  );

  // Test 5.6: Unknown routes return JSON 404 instead of Express HTML 404
  const res5_6 = await apiRequest(`/route-that-does-not-exist-at-all`);
  const pass5_6 =
    res5_6.status === 404 &&
    res5_6.body !== null &&
    typeof res5_6.body === "object" &&
    res5_6.body?.error === "Ruta no encontrada.";

  recordResult(
    "Regression (Route Handling)",
    "5.6 Unknown routes return JSON 404 instead of Express default HTML",
    pass5_6,
    res5_6
  );

  // ============================================================================
  // SUMMARY
  // ============================================================================
  console.log("\n================================================================================");
  console.log("📊 TEST EXECUTION SUMMARY");
  console.log("================================================================================");
  console.log(`Total Tests Run: ${totalTests}`);
  console.log(`Passed:          ${passedTests} (${Math.round((passedTests / totalTests) * 100)}%)`);
  console.log(`Failed:          ${failedTests}`);
  console.log("================================================================================\n");

  try {
    await cleanTestData();
  } catch (cleanupErr) {
    console.warn("Cleanup warning:", cleanupErr.message);
  }

  await pool.end();

  if (failedTests > 0) {
    process.exit(1);
  }
}

runTestSuite().catch((err) => {
  console.error("Fatal error during test run:", err);
  pool.end();
  process.exit(1);
});
