upstream frontend_upstream { server frontend:5173; }
upstream auth_upstream     { server auth-service:3001; }
upstream empl_upstream     { server employee-service:3002; }
upstream recr_upstream     { server recruitment-service:3003; }
upstream att_upstream      { server attendance-service:3004; }
upstream comp_upstream     { server compensation-service:3005; }
upstream perf_upstream     { server performance-service:3006; }
upstream notf_upstream     { server notification-service:3007; }

server {
    listen 80;

    # Headers generales
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # Frontend
    location / {
        proxy_pass http://frontend_upstream;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Backend
    location /api/auth/ {
        proxy_pass http://auth_upstream/;
    }

    location /api/empl/ {
        proxy_pass http://empl_upstream/;
    }

    location /api/recr/ {
        proxy_pass http://recr_upstream/;
    }

    location /api/att/ {
        proxy_pass http://att_upstream/;
    }

    location /api/comp/ {
        proxy_pass http://comp_upstream/;
    }

    location /api/perf/ {
        proxy_pass http://perf_upstream/;
    }

    location /api/notf/ {
        proxy_pass http://notf_upstream/;
    }
}