FROM node:20-alpine

RUN apk add --no-cache graphicsmagick ghostscript

RUN apk add --no-cache \
    libreoffice \
    poppler-utils \
    ghostscript \
    graphicsmagick \
    ttf-dejavu

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

CMD ["npm", "run", "dev"]